Front end
CS-Club-Medical-Webapp/HealthHQ pull request #9
Opened 2020-10-29 16:24 UTC by farhanhaider1

HTML and CSS for left semi-circle

2020-10-29 16:30 UTC, farhanhaider1 commented on style.css
> +}
this will reset all existing padding

2020-11-02 03:53 UTC, Tenzilla requested changes
We could change a little

2020-11-02 03:53 UTC, Tenzilla commented on style.css
> +}
Did you mean style.css will reset all existing padding?

2020-11-02 03:53 UTC, Tenzilla commented on index.html
> +    <meta name="HealthHq" content="width=device-width, initial-scale=1.0">
Should we do "HealthHQ" or "HealthHq"?

2020-11-02 15:23 UTC, farhanhaider1 commented on style.css
> +}
yeah sometimes a stupid white space will appear on top of the header! This will take care of it...

2020-11-02 15:23 UTC, farhanhaider1 commented on index.html
> +    <meta name="HealthHq" content="width=device-width, initial-scale=1.0">
umm i think HQ will be better

2020-11-05 14:56 UTC, farhanhaider1 commented
update to HealthHQ
The circle is ok!

2020-11-05 14:56 UTC, merged